const batches = [
  {
    id: 1,
    name: "The Temps Commission",
    src: "https://com.bimago.media/media/catalog/image/view/product/89856/role/image/size/1500x2240/type/ft-osmr-ng1/f6c607e29956d55da919e89ee3f74fef.webp",
    desc: "As the population of the world is significantly increasing year after year, it became greatly disproportionate to the available resources that can sustain human life. In a dystopian society in 2169, every person stops aging at 25, but is genetically engineered to live off the clock installed on their forearm at birth. Everyone is given exactly 365 days on the clock and the time will start ticking away as soon as they come of age. \n\nTo control the population, the country, New Greenwich, is divided into Time Zones. \n\nThe poor inhabit Time Zone 1; manual labourers who get paid measly, hardly sustaining their living with the ever increasing inflation. Citizens in the Time Zone live off a day's worth of time, often as not, expiring on the streets when their hard-earned time ticks to its last second. \n\nIn Time Zone 10, the wealth lived lavishly. With centuries to millennia of time in their clocks, they essentially live as immortals; flocking in casinos day in and out, hosting and attending grand parties every night.",
    tags: "dystopian, competition, time as currency, games",
    quote: "The rich can live forever, the poor die young.",
    codename: ["Time Keepers", "Citizens"],
    admins: "Martin Walker, Jerry Rogers",
    members: [
      "T01-001: Iekami Getsuryuu",
      "T01-002: Alessia Devynn Llywelyn",
      "T01-003: Theodore Julien Foster",
      "T01-004: Estelle Illiana",
      "T01-005: W***** R*********",
      "T01-006: Beatrice Amelia",
      "T01-007: S**** S********",
      "T01-008: Maxine Briar",
      "T01-009: Evander Damaris",
      "T01-010: Nala Rivers",
      "T01-011: Valerian Ford",
      "T01-012: E****** I** A****",
      "T01-013: D*** L******",
      "T01-014: Nicolette Bronchard",
      "T01-015: C****** E*****",
      "T01-016: Jeannine",
      "T01-017: Caspian Wilder",
      "T01-018: Martha Ivory Baker",
      "T01-019: Morgan Lloyd",
      "T01-020: Madeleine Hampton",
      "T01-021: Zion Alessandre Wilde",
      "T01-022: Samara Dardenne",
      "T01-023: R**** C******",
      "T01-024: Everett Sun",
      "T01-025: O*** D****** A*******",
      "T01-026: A**** L** S*******",
      "T01-027: Ikumi Naoya",
      "T01-028: A***** H*****",
      "T01-029: O***** L***",
      "T01-030: A**** R********",
    ],
    testimony: {
      who: "Onyx Desiree Aphelion",
      pic: "/onyx.png",
      highlight:
        "The movie reference was so creatively placed,\nit was like a combination of In Time and The Hunger Games?",
      says: "TempsCommission was one of the first few agencies that awakened my love and passion to plot and develop my original character. I was given so many chances to socialize in the way too, and it made me gain a lot of new friends. The movie reference was so creatively placed, it was like a combination of Time and The Hunger Games? I love how the second part was centered on rebellion and revolution. Just as I thought it couldn’t get any better, you guys exceeded all my expectations and gave us a very enjoyable experience!",
    },
  },
  {
    id: 2,
    name: "Defeat the System",
    src: "https://i0.wp.com/www.additudemag.com/wp-content/uploads/2021/01/GettyImages-1145171942.jpg?w=1920&crop=0%2C0px%2C100%2C1081px&ssl=1",
    desc: "Set two years later after The Temps Commission, the Citizens did not live any different from the lives they signed themselves up to the Games for; they were rewarded too little, greatly out of proportion to their agonising efforts to be the victors of The Annual Time Games 2169. \n\nThey still work manual labour for measly pay, see people time out on the streets, live in a day's worth of time in their clocks, and put up with the blatant injustice of the system. While their lives were the same, unlike before, The Citizens were outraged. \n\nThey braved out and formed an alliance among each other. Little by little, they built CTZN from the ground up, a secret organisation, in which they work together to shape the perfect scheme to ultimately blow up the system. \n\nThus far, they have advanced to Time Zone 3 and are in need of a new master plan and resources to continue their long journey to Time Zone 10 and eventually Time Zone 0 where the rich dwells and Temps Commission lies, respectively. \n\nThey have one chance to bring about the collapse of of persisting injustice in New Greenwich. Will the Citizens succeed and defeat the system?.",
    tags: "dystopian, uprising",
    quote: "Will the Citizens succeed and defeat the system?",
    codename: ["Time Keepers", "Citizens"],
    admins: "Martin Walker, Jerry Rogers",
    members: [
      "T01-001: Iekami Getsuryuu",
      "T01-002: Alessia Devynn Llywelyn",
      "T01-003: Theodore Julien Foster",
      "T01-004: Estelle Illiana",
      "T01-006: Beatrice Amelia",
      "T01-008: Maxine Briar",
      "T01-009: Evander Damaris",
      "T01-010: Nala Rivers",
      "T01-011: Valerian Ford",
      "T01-013: D*** L******",
      "T01-015: C***** E*****",
      "T01-016: Liliane Hayes",
      "T01-018: Martha Ivory Baker",
      "T01-020: Madeleine Hampton",
      "T01-022: Samara Dardenne",
      "T01-023: R**** C******",
      "T01-024: Everett Sun",
      "T01-025: O*** D****** A*******",
      "T01-026: A**** L** S*******",
      "T01-027: Ikumi Naoya",
      "T01-029: O***** L***",
    ],
    testimony: {
      who: "Iekami Getsuryuu",
      pic: "/ryuu.png",
      highlight:
        "I’m glad I was there to witness all the new games an agency ever created.",
      says: "As a sequel from the first, Defeat The System had me running for my life with more intense tasks. This batch is also the first of many other tasks where we are required to have relations within the batch. I didn’t expect myself to be able to reach the Time Zones 0 at the end, but I’m glad I was there to witness all the new games an agency ever created. 100% would fight against Martin as timekeeper again.",
    },
  },
  {
    id: 3,
    name: "Warwick Intelligence Service",
    src: "https://ras-nsa.ca/wp-content/uploads/2022/01/Renseignement.jpg",
    desc: "The world had gradually become wicked year after year when the millennium began. Legions of anti-government groups and crime syndicates came to the surface, operating to resist the government and commit offences for their own gain, resulting to the compromise of the people's right to security. \n\nEradicating these groups is the government's longstanding problem. Their modus operandi evolved through the years. Beginning the year 2022, they started communicating openly through radio transmissions, but in unspecified codes and ciphers, making it difficult for the government to locate their hideouts and intercept the planned attacks. \n\nTo help with the problem, Warwick Intelligence Service is set to form a task force to work towards the complete wipeout of the anonymous groups and ultimately restoring the peace and order in Ostden.",
    tags: "military intelligence, ciphers and codes",
    quote: "Protecting the country, the people, and their interests.",
    codename: ["Task Force Commanders", "Agents"],
    admins: "Martin Walker, Alexander Nolan",
    members: [
      "WIS-003: Iekami Getsuryuu",
      "WIS-004: Nala Rivers",
      "WIS-005: Evander Damaris",
      "WIS-006: Liliane Haynes",
      "WIS-007: O*** D****** A*******",
      "WIS-008: Dylan Briar",
      "WIS-009: Roman Caden Won",
      "WIS-010: Samara Dardenne",
      "WIS-011: Valerian Ford",
      "WIS-012: Enid Lea Schwartz",
      "WIS-013: V***** T******",
      "WIS-014: Madeleine Hampton",
      "WIS-015: Atlas Dufort",
      "WIS-016: Veronica Quinn",
      "WIS-017: Leonard Touissant",
      "WIS-018: S***** L******",
      "WIS-019: Maximus Oliver Wang",
      "WIS-020: Eveline Mae",
      "WIS-021: Xavier Lucille Easton",
      "WIS-022: Arianne Adler",
      "WIS-023: Maximilian Nathaniel",
      "WIS-024: S**** B******",
      "WIS-025: R**** I****** H*******",
      "WIS-026: Chrys Aubine",
      "WIS-027: Killian Pierce",
      "WIS-028: Trixie Leighton",
      "WIS-029: Dalton Leauregard",
      "WIS-030: Judith Jenina Rainsford",
      "WIS-031: Zero Hans Kaizer",
      "WIS-032: A****** Z***** H************",
      "WIS-033: S******* A******",
      "WIS-034: Lunetta Selene",
      "WIS-035: Zion Rand Carter",
      "WIS-036: Keiko",
    ],
    testimony: {
      who: "Nala Rivers",
      pic: "/nala.png",
      highlight:
        "One thing about Walker Archives, they will give you the chance to be someone you wouldn't even think about writing yourself.",
      says: "I loved playing agent! One thing about Walker Archives, they will give you the chance to be someone you wouldn't even think about writing yourself. Me, a translator? I wouldn't have imagined myself as a translator without their storyline and guidance. Oh, I had a badass codename too. The Ivy.",
    },
  },
  {
    id: 4,
    name: "Blanc Private Detectives",
    src: "https://www.voffice.com.sg/wp-content/uploads/2024/09/private-detective-services-1024x585.jpg",
    desc: "New York City is one of the renowned cities in the world, if not the most. It is the home to a diverse population, plethora of skyscrapers tenanted by high-flying businesses, and of course, the first thing that pops into one's mind at the mention of New York City, the turquoise monument of the Statue of Liberty. \n\nThe Big Apple, the nickname they have given the darling city, inspires. Many renowned personalities were born in the city—Al Pacino, Marvel actors Robert Downey Jr. and Scarlet Johansson, the Bloombergs and the Rockefellers, and the list goes on. It's a place where you can build, work on, and live the success you have always dreamed of. But despite that, it is called a concrete jungle for a reason. Many have attempted to live in the bustling metropolis, but only the hustlers and go-getters remain; only those who can keep up with the fast-paced, ever-changing way of life can survive. \n\nLiving in New York City is a game of hit and miss. You break your back beating your future into shape; you have a high-paying job, you live in a high-ceiling, spacious apartment in the heart of Manhattan, and you have several connections with people in power, but there's no guarantee that these will remain yours forever. \n\nIf one day you wake up and you find yourself in the list suspects of a high profile murder, what measures are you going to take to save yourself, your material possessions, and your reputation?",
    tags: "murder mystery, city life",
    quote:
      "What measures are you going to take to save yourself, your material possessions, and your reputation?",
    codename: ["Private Detectives", "Suspects"],
    admins: "Martin Walker, Jerry Rogers",
    members: [
      "S-001: Iekami Getsuryuu",
      "S-002: R****** K***",
      "S-003: Maxine Briar",
      "S-004: Elise Marlène",
      "S-005: Gwynyth Olivia",
      "S-006: E****** S**",
      "S-007: H******** A****** R****",
      "S-008: Dezion E. Elford",
      "S-009: Veronica Quinn",
      "S-010: Emery Sun",
      "S-011: Koshino Deura",
      "S-012: Eleanor Forger",
      "S-013: Maximillian Redwood",
      "S-014: Evander Damaris",
      "S-015: K****** R****",
      "S-016: August Liu",
      "S-017: Khione Aetherius",
      "S-018: Reo Eridanus Sterling",
      "S-019: Valerian Ford",
      "S-020: Benjamin Chase",
      "S-021: Mellissa Cathareau",
      "S-022: Viviane Leung",
      "S-023: Kevander Hugo",
      "S-024: J****** S*****",
      "S-025: Finn O'Brien",
      "S-026: Antoinette Vivienne Forger",
      "S-027: H***** E******",
      "S-028: L***** M****",
      "S-029: Avery Kim",
      "S-030: Rhesh Lysander",
      "S-031: Selene Reverie",
      "S-032: Henry Kane",
    ],
    testimony: {
      who: "Valerian Ford",
      pic: "/valerian.png",
      highlight:
        "I remember trying to piece together the clues, acting like I had it all figured out, only to be hit with a jaw-dropping twist at the end.",
      says: "Blanc Private Detective—it was one hell of a ride, in the best way. Cracking riddles and suspecting each other—I remember trying to piece together the clues, acting like I had it all figured out, only to be hit with a jaw-dropping twist at the end. We love a good twist, especially when it involves a tangled romance between beautiful women and crime. Frankly speaking, Alexander Nolan deserved his tragic end!",
    },
  },
  {
    id: 5,
    name: "Majority Feed",
    src: "https://balkaninsight.com/wp-content/uploads/2020/07/kon-karampelas-9BbkkdurAnU-unsplash-e1595335692887-1280x720.jpg",
    desc: "In an alternate universe, the world adopts a government system that practices an absolute unstructured democracy where perks and punishments of the people are determined solely by individual and public opinion. Every person, upon turning 18, puts on a vote badge and people around them, regardless of the age, can give them an upvote or a downvote in person or online, depending on how one’s action was taken or perceived. Often than not, as these perceptions are shallow and heavily influenced by social media and group pressure, people strive to please the society. However, despite the efforts, there are still people who are sentenced to go through “social correction”, the term the government uses to tone down the process of neurosurgical treatment to brainwash the convicted citizens, albeit unjustly. \n\nThe Majority Feed, an online video-sharing and voting platform airs 24/7 on national television. The platform is accessible on mobile devices, too, where the people can cast their votes. It streams “viral” videos that were taken by the people of others and the people in the said videos will then be subject to public voting. The vote of the majority, upon reaching the threshold, will determine their fate.",
    tags: "alternate universe, unstructured democracy, mob mentality",
    quote:
      "Are you brave enough to step into a society that's greatly influenced by mob mentality?",
    codename: ["Publicity Officers", "MFers"],
    admins: "Martin Walker, Jerry Rogers",
    members: [
      "@correyfleur: Blair Coronette Pugh",
      "@easycasey: Casey Winslow",
      "@Damience: Damien Gauthier",
      "@deardarla: Darla Frances Spencer",
      "@dezionel: Dezion Emmanuel",
      "@elisesile: Elise Marlene",
      "@finnotfine: Finn O'Brien",
      "@henrykane: Henry Kane",
      "@drag.on: Iekami Getsuryuu",
      "@reimogened: Imogen Jade Zetkin",
      "@Kaoririe: Irie Kaori",
      "@scarlatte: Judith Jenina Millers",
      "@koshinodeura: Koshino Deura",
      "@Skywashere: Langit Malam",
      "@leogendary: Leonidas Liu-Watterson",
      "@maxlaurent: Max Laurent",
      "@horchatapapi: Miguel Ãngel Cruz-Iglesias",
      "@Nala: Nala Rivers",
      "@cassiuscars: Nathaniel Cassius Syndergaard",
      "@oceabreeze: Ocean Kaslana Rue",
      "@NO1LIKEME: Onyx D. Aphelion",
      "@piptheheart: Piper Hearts",
      "@weREOwolf: Reo Eridanus Sterling",
      "@TeamRhesh: Rhesh Lysander",
      "@unearthed: Roman Lee",
      "@ontheotrack: Theodore Julien Foster",
      "@quinnbee: Veronica Quinn",
      "@cestlaviv: Viviane Leung",
    ],
    testimony: {
      who: "Koshino Deura",
      pic: "/koko.png",
      highlight:
        "I had heard that W is famous for their riddles, but surprisingly, Majority Feed still did amazingly without them.",
      says: "I was still considered a newcomer when Majority Feed happened, and it was only my second batch, as I remember. I had heard that W is famous for their riddles, but surprisingly, Majority Feed still did amazingly without them. It had a social media theme, and I enjoyed seeing people's secrets and embarrassing moments, as well as competing to receive upvotes. I was one of the winners by the end of the batch, so it's understandable why I love it, honestly!",
    },
  },
  {
    id: 6,
    name: "The Bereuenberg",
    src: "https://images.squarespace-cdn.com/content/53dd6676e4b0fedfbc26ea91/1500920648217-5ECA5F7CEYBT4TZ5Y3UF/IMG_3280+copy.jpg?format=1500w&content-type=image%2Fjpeg",
    desc: "Bereuenburg, a small town in Georgia, USA, is home to 7,791 residents, ranging from those who grew up in the town to those who chose to call it their home. The town is known for its pleasant weather, natural beauty, and, of course, those delicious peaches. It's a close-knit community where everyone either knows their neighbors or shares some familial connection. \n\nDespite its modest population, Bereuenburg offers everything the locals need: schools, grocery stores, gas stations, shops, pharmacies—you name it. That's why people choose to remain right in town. \n\nFor the working class, they either run their own businesses within the town, work remotely, or commute to neighboring cities like Atlanta, Valdosta, and Tucker. \n\nTruly, there's no place quite like home. It offers both familiarity and security. Until it doesn't. \n\nWhat would you do if one day, a wave of murders and kidnappings struck the town, where everyone knew each other, one way or another? The town that once provided a sense of safety and security has become a breeding ground for a string of heinous acts. The mystery of who the perpetrators could be, even in broad daylight, weigh heavily on the townspeople. They could be your family, friends, and neighbours.",
    tags: "crimes, mystery, small town",
    quote: "Keep the doors shut and your one eye open. You could be next.",
    codename: ["Detectives", "Townspeople"],
    admins: "Martin Walker, Jerry Rogers",
    members: [
      "BRN-001: Aaralyne Cyra Anya",
      "BRN-002: Kaleia Serenity Lovelace",
      "BRN-003: Max Laurent",
      "BRN-004: Viviane Leung",
      "BRN-005: Ariel Nieven Levisay",
      "BRN-006: Rhesh Lysander",
      "BRN-007: Axton Reed",
      "BRN-008: Damien Janvier",
      "BRN-009: Mellissa Cathareau Millers",
      "BRN-010: Lynne Odessa Kirstein",
      "BRN-011: Eleianna Ivy Jacqueline",
      "BRN-012: Veronica Quinn",
      "BRN-013: Sazellene Gradie Aberforth",
      "BRN-014: Leonard Huo",
      "BRN-015: L** A******",
      "BRN-016: Sam Keane",
      "BRN-017: Eira Noelle Villeneuve",
      "BRN-018: G******** A********",
      "BRN-019: Lucienne Ryoo",
      "BRN-020: Kaeto",
      "BRN-021: Colleena Zoe",
      "BRN-022: Dezion Emmanuel",
      "BRN-023: Josephine Ingrid Alexandra",
      "BRN-024: Cassius Lim Navarone",
      "BRN-025: Eden Desjardins",
      "BRN-026: Henry Kane",
      "BRN-027: Finn O'Brien",
      "BRN-028: Kit Sommers",
      "BRN-029: Elio Valentine Kim",
      "BRN-030: Edith Grace Millers",
      "BRN-031: James Nathanael Roosevelt",
      "BRN-032: R******* C*****",
      "BRN-033: S**** G****",
    ],
    testimony: {
      who: "Leonard Huo",
      pic: "/leo.png",
      highlight:
        "Watching things unfold as I laid out the cards was quite an experience; it was both thrilling and nerve-wracking.",
      says: "Definitely my favorite batch for a reason (and not just because I got to be the main and only antagonist). Everyone cooked REALLY hard even though I too was being cooked, grilled, whatever you name it. Watching things unfold as I laid out the cards was quite an experience; it was both thrilling and nerve-wracking. Hands down one of my top favorite moments of writing in the community. To this day, I’m still amazed at how W thought of the idea to create Bereuenburg in the first place, let alone the riddes, the lore and everything else. Will I do it again? 100000/100. W Forever.",
    },
  },
  {
    id: 7,
    name: "The Grand Arcadia",
    src: "https://www.mues.us/wp-content/uploads/2021/03/exterior_new-scaled-e1616805070908-2048x1024.jpg",
    desc: "Situated within South Korea's sprawling metropolis of Seoul is a haven of countryside living where hundreds have found their home. The Grand Arcadia, an apartment complex comprised of three midrise buildings, offers a taste of rural life amidst the urban landscape. Sought after by many for its ambiance, among other features, including trees carefully preserved by its developers, lush greenery, and a shield from the city's constant buzz. \n\nMany eagerly wait in line for a chance to call The Grand Arcadia their home, joining the waitlist for an opportunity to reside in this highly coveted complex. Despite its many charms, what sets The Grand Arcadia apart is its reasonable rent. However, the complex has its own unique criteria for selecting tenants. Wealth, power, or fame won't give you an advantage here. They have specific rules, and failing to meet them could mean packing your bags. \n\nOnce you've secured a spot, it's all about playing by their rules. Residents bend over backward to ensure they continue meeting those criteria. After all, securing a favorable standing within The Grand Arcadia, regardless of the efforts required, is the gateway to remaining within its walls that offer peace amidst the city's hustle and bustle.",
    tags: "slice of life, apartment AU",
    quote:
      "One thing's certain: you will get to experience everything that The Grand Arcadia has to offer—reasonable rent, well-kept amenities, a great community, everything.",
    codename: ["Custodians", "Tenants"],
    admins: "Jerry Rogers, Alexander Nolan, Martin Walker",
    members: [
      "TGA-101: Kang Ilho",
      "TGA-102: Cassius Lim",
      "TGA-103: Akihiko Ryuji",
      "TGA-104: Dominique Beischel",
      "TGA-105: Ilsa Vaughn",
      "TGA-106: Kaeto",
      "TGA-107: Kaiden Zhang",
      "TGA-108: Kang Yuchan",
      "TGA-209A: Koshino Deura",
      "TGA-209B: Ryuzaki Heidi",
      "TGA-210A: Claude Remy",
      "TGA-210B: Carl Lee",
      "TGA-211A: Colleena Zoe",
      "TGA-211B: Sam Keane",
      "TGA-212A: Elise Marlene",
      "TGA-212B: Kit Sommers",
      "TGA-213A: Galilea Lee",
      "TGA-213B: Khione Aehterius",
      "TGA-214: Josephine Ingrid Alexandra",
      "TGA-214B: Leonidas Liu",
      "TGA-215A: Madeline March",
      "TGA-215B: Atlas Sheathes",
      "TGA-216A: Riccardo Barone",
      "TGA-216B: Celia March",
      "TGA-217A: Ravel Jade",
      "TGA-217B: Maevis Mourish",
      "TGA-218A: Jett Thorns",
      "TGA-218B: Johnny Wolff",
      "TGA-319: Ocean Kaslana Rue",
      "TGA-320: Reagan Yeong",
      "TGA-321: Ace Daryl",
      "TGA-322: Arthur Douglas",
      "TGA-323: Jacqueline Yelaene",
      "TGA-324: Jonah Zhang",
      "TGA-325: Vicky Marie",
    ],
    testimony: {
      who: "Claude Remy Crawford",
      pic: "/claude.png",
      highlight:
        "But it’s not Walker if they didn’t add up a twist in the plot which is gagged me so hard!",
      says: "Actually TGA wasn’t not the first batch I joined, but if you asked me to list down my favorite batches then this one will go straight to #1! I will give it 9.5/10 (minus 0.5 points because I was stuck there). They didn’t lie when the brought the apartment theme with a ‘unique criteria’ for the tenants because everyone in TGA are unique and funny—I got a lot of fun interacting, playing and writing here. But it’s not Walker if they didn’t add up a twist in the plot which is gagged me so hard!",
    },
  },
  {
    id: 8,
    name: "The Route 666",
    src: "https://i.pinimg.com/originals/27/79/10/277910ddcb5bb8f784d0301dc2226d7c.jpg",
    desc: "The world had been whispering for a while, its pronouncements subtle but undeniable. The relentless afternoon sun burned hotter than ever. Volcanic tremors rumbled with an unsettling frequency. Oceans, once vast and calming, now lapped hungrily at the edges of coastal cities. Resources, once plentiful, became a source of anxious whispers in every corner of the globe. Yet, for most, it was simply life becoming demonstrably harder, a trend etched year after year in the lines on their faces. \n\nThen, for twenty-four seemingly random individuals scattered across the states, the whispers morphed into a scream. Delivered by unknown hands, a letter arrived at their doorsteps. No words, no explanation, just a chilling sequence of numbers scrawled across the page. These numbers, they soon discovered, were not a cruel prank, but a desperate plea. A message from a future teetering on the brink, a future where 2024 marked the year the flame of humanity flickered and died. The numbers, they realised with a jolt of terror and a sliver of hope, were not a way to rewrite history, but a chance to rewrite the ending. Not to reverse the damage, but to slow the inevitable, to buy the world a breath, a chance to face its fate not with a whimper, but with a resolute, desperate fight. \n\nIt was at The Route 666 Diner that these twenty-four strangers gathered, brought together by a message from a dying future, to conspire how to slow the inevitable.",
    tags: "science fiction, survival, dystopian",
    quote: "We're gonna live like it's the end of the world.",
    codename: ["Diner crews", "Members"],
    admins: "Martin Walker, Evangeline Harper",
    members: [
      "Adrain Myles Schandré",
      "A******** K******",
      "Ares Evander Wayne",
      "Ariel Nieven Levisay",
      "Yvvone Marie Liu",
      "Viviane Leung",
      "Viridian Jo",
      "V******* J****** C****",
      "Atheana Madeline Reign",
      "B******* C****",
      "D***** E*******",
      "Elio Valentine Kim",
      "Tanaka Keigo",
      "Scarlett Artemis Vognsen",
      "Millie Horne",
      "N*** D*** R*****",
      "Ezra Hayes",
      "Haru Lee",
      "Helena Elmeira",
      "Hera Remington",
      "Lariette Salomé",
      "Kuroshima Miko",
      "I***** E*******",
      "Jelena Ruth",
    ],
    testimony: {
      who: "Atheana Madeline Reign",
      pic: "/atheana.png",
      highlight:
        "My brain got a workout in the most unexpected and entertaining ways!",
      says: "I finally jumped into Route 666 after skipping a bunch of W batches, and honestly, I was a little nervous. It had been ages since I joined an agency with plotting and riddle concepts, so I thought I’d be totally out of sync. But, it was a BLAST. The thrill of cracking the riddles, the anticipation of what surprise would drop next during the batch, and don’t even get me started on the plot twists. My brain got a workout in the most unexpected and entertaining ways. Seriously, 10/10 would do it all over again!",
    },
  },
  {
    id: 9,
    name: "Blackthorn Manor",
    src: "https://www.bretfortonmanor.co.uk/wp-content/uploads/2024/02/Manor-1.jpg",
    desc: "The Blackthorn Manor, a Nolan grand estate in the heart of Northamptonshire, England... \n\nBlackthorn Manor, the Nolan grand estate in the heart of Northamptonshire, England, stands as a monument to a bygone era. Constructed in the 1400s, its medieval architecture has withstood the passage of time, its original character preserved despite necessary renovations and repairs. This grand estate, a proof of the family’s enduring wealth and prominence, has remained in their hands for generations, a private residence untouched by time. \n\nThe Nolan family’s story is one of grit and determination. Their origins as builders in the 1300s, though humble, were marked by a strong work ethic that has echoed through the generations. Today, Edmund Nolan, the head of the family, enjoys the fruits of his ancestors’ labour. His family’s wealth is so vast that even his great-granddaughter’s daughter could live a life of comfort without ever needing to work. \n\nDespite their immense wealth, the Nolans are, in many ways, a typical family, albeit one with a unique and extraordinary history. Each summer, they open their doors to guests, welcoming them to Blackthorn Manor for lavish parties and banquets. They offer warmth and hospitality, creating a sense of home for those fortunate enough to be invited. \n\nAnd as August arrives, the summer season is in full swing at Blackthorn Manor. The air is thick with the anticipation of laughter, music, and the taste of a life they can only dream of possessing. \n\nBut behind the opulence of Blackthorn Manor and the charming smiles of the Nolan family, a darker truth lurks. Just like any other family, the Nolans have their own skeletons in the cupboard. Secrets, buried deep within the manor’s ancient walls, await discovery. And perhaps, beneath their polished exterior lies a darker side, a family that looks at everyone with disdain to match the manor’s imposing presence. \n\nAre you brave enough to step into a summer of opulence, filled with lavish parties, sun-soaked days, and sumptuous feasts, all while working your way to the top, uncovering secrets that could be your ticket to power? If so, come to Blackthorn.",
    tags: "drama, betrayal, obsession, class",
    quote: "Come to Blackthorn.",
    codename: ["Butlers", "Members"],
    admins: "Martin Walker, Jerry Rogers",
    members: [
      "Heidi Ejder",
      "Koshino Deura",
      "Edith Grace Lockwood",
      "Riccardo Barone",
      "Henry Kane",
      "Lilliane Liu",
      "Josephine Ingrid Alexandra",
      "S** K****",
      "Colleena Zoe",
      "Valerian Saint Mleux",
      "Agus Asparagus",
      "Cassius Lim Navarone",
      "Piper Foxx",
      "Shiloh Hayes Nightbloom",
      "Josiah Ecclestone",
      "Katya Solène Lyons",
      "Alexander",
      "Claude Remy Crawford",
      "Killian Reed",
      "Ryder Vaughn",
      "V***** B******",
      "Maizel Leonhart",
      "Elizabeth Rue Wagner",
      "Reo Eridanus Sterling",
      "Deaglan Myriad Zecharias",
      "R****-P***** T*******",
      "Shalimar Amari",
      "Johnny Louise Wolff",
      "A***** D*******",
      "Kiara Grace",
      "Mezoya Liu",
      "Ocean Kaslana Rue",
      "Gallio Magnus Chevalier",
      "Kevander Hugo",
      "Jett Thorns",
    ],
    testimony: {
      who: "Heidi Ejder",
      pic: "/heidi.png",
      highlight:
        "Would do it again and again tirelessly and be the Holmes of the year.",
      says: "Blackthorn Manor was a blast for me! It gives me a challenge to unveil everyone’s secrets by myself. It had me on the edge of my seat for ten days, waiting for any twists and turns and clues that may have helped me solve the secret with hundred percent accuracy to be right. Would do it again and again tirelessly and be the Holmes of the year.",
    },
  },
  {
    id: 10,
    name: "04 Friedhof",
    src: "/4f.png",
    desc: "Housing has become nearly impossible to secure in this generation—the prices are beyond our reach. But what would you do if a six-bedroom mansion, hidden deep in the desolate woods outside New York, suddenly appeared on the market at a strangely low price? The listing notes it's been vacant for over two years. When you ask your real estate agent why, she can’t give you a straight answer. All she knows is that the property tax has gone unpaid, and it's being sold for next to nothing to cover the debt. A steal in this economy. Who wouldn’t be tempted? \n\nWinter has set in, blanketing the roads in as you drive to the property. The air turns colder, your phone signal fades, and the woods grow thicker as you approach the mansion—its dark silhoutte looming from the snow, isolated and forgotten, as if waiting for someone like you to disturb its silence. \n\nYou’re not alone; 23 other visitors linger around the property, drawn by the mansion’s beauty, allure, and mystery. This is a first-class home at a price that won’t break the bank—steeped in eerie history. Assuming everyone’s here for the same reason, you soon find yourself caught in a game of rivalry and perhaps... survival amid the snowstorm. \n\nWill you be able to claim the mansion for yourself, or will someone else beat you to it?",
    tags: "mystery, thriller",
    quote: "What's the price of the mansion?",
    codename: ["Also trapped inside", "Members"],
    admins: "Evangeline Harper, Serena Morgan, Martin Walker",
    members: [
      "Aaron Ford Leneghan",
      "Alan Montgomery",
      "Alia Yrving",
      "Ariel Nieven Levisay",
      "Camille Margaux",
      "Diana Fincher",
      "Dominique Blue Rose Eanes",
      "Elleonaire van Dijk",
      "Ethan Snyder",
      "Ezra Hayes",
      "Hamengku Alurisjad",
      "Ieiri Seigen",
      "Ilsa Vaughn",
      "Irene Liu",
      "Isabel Reyes",
      "Keigo Dash-Tanaka",
      "Kiedis Nox",
      "Laura Kinney",
      "Lee Seulong/Dew Lee",
      "Maivella Aoki",
      "Millie Horne",
      "Misora Katagiri",
      "Naomi Evangeline",
      "Nero Julien",
      "Niko Dash-Tanaka",
      "Rhaenyra",
      "Sergio Ezekiel",
      "Uno Jovanovic",
      "Venetia Roscent",
      "Victoire Lyra Lee",
    ],
    testimony: {
      who: "Keigo Dash-Tanaka",
      pic: "/keigo.png",
      highlight: "10/10 would recommend Walker to friends.",
      says: "This batch was fun. I love that there’s always so much to work around when it comes to the classic murder mystery trope of being stranded in the middle of nowhere with a group of strangers. Like, we could’ve been found family but y’all playin’ and decided to be criminals instead! I liked solving the riddles and connecting the dots, though I didn’t expect the price of the mansion to literally be death. 10/10 would recommend Walker to friends as long as you guys promise not to kill me again.",
    },
  },
];

const members = [
  { id: "0101", name: "Iekami Getsuryuu" },
  { id: "0102", name: "Cassius Lim Navarone" },
  { id: "0103", name: "Onyx Desiree Aphelion" },
  { id: "0104", name: "Valerian Ford" },
  { id: "0105", name: "Hera Remington" },
  { id: "0106", name: "Samara Dardenne" },
  { id: "0107", name: "Maxine Briar" },
  { id: "0108", name: "Nicolette Bronchard" },
  { id: "0109", name: "Nala Rivers" },
  { id: "0301", name: "Veronica Quinn" },
  { id: "0302", name: "Eveline Mae" },
  { id: "0303", name: "Emery Sun-Everheart" },
  { id: "0304", name: "Judith Jenina Millers" },
  { id: "0305", name: "Lunetta Selene" },
  { id: "0401", name: "Koshino Deura" },
  { id: "0402", name: "Benjamin Chase" },
  { id: "0403", name: "Lillianne Liu" },
  { id: "0404", name: "Elise Marlene" },
  { id: "0405", name: "Gwynyth Olivia Lynford" },
  { id: "0406", name: "Henry Kane" },
  { id: "0407", name: "Helena Elmeira" },
  { id: "0408", name: "Finn O’Brien" },
  { id: "0409", name: "Khione Aetherius" },
  { id: "0410", name: "Reo Eridanus Sterling" },
  { id: "0411", name: "Viviane Leung" },
  { id: "0412", name: "Kevander Hugo" },
  { id: "0413", name: "Dezion Emmanuel" },
  { id: "0414", name: "Joanne Evangeline Skylar" },
  { id: "0501", name: "Leonidas Liu" },
  { id: "0502", name: "Darla Frances Spencer" },
  { id: "0503", name: "Ocean Kaslana Rue" },
  { id: "0504", name: "Piper Adams" },
  { id: "0505", name: "Irie Kaori" },
  { id: "0601", name: "Elio Valentine Kim" },
  { id: "0602", name: "Ariel Nieven Levisay" },
  { id: "0603", name: "Eden Desjardins" },
  { id: "0604", name: "Edith Grace" },
  { id: "0605", name: "Eira Noelle Villeneuve" },
  { id: "0606", name: "Colleena Zoe" },
  { id: "0607", name: "Sam Keane" },
  { id: "0608", name: "Kaeto" },
  { id: "0609", name: "Visenya" },
  { id: "0610", name: "Sarah Gibbs" },
  { id: "0611", name: "Eleianna Ivy Jacqueline" },
  { id: "0612", name: "Lynne Odessa Kirstein" },
  { id: "0701", name: "Kaiden Zhang" },
  { id: "0702", name: "Jett Thorns" },
  { id: "0703", name: "Claude Remy Crawford" },
  { id: "0704", name: "Ilsa Vaughn" },
  { id: "0705", name: "Johnny LouIse Wolff" },
  { id: "0706", name: "Maevis Katz Mourish" },
  { id: "0707", name: "Uno Jovanovic" },
  { id: "0708", name: "Ace Daryl" },
  { id: "0801", name: "Heidi Ejder" },
  { id: "0802", name: "Millie Horne" },
  { id: "0803", name: "Ezra Hayes" },
  { id: "0804", name: "Haru Lee" },
  { id: "0805", name: "Riccardo Barone" },
  { id: "0806", name: "Dominique Blue Rose" },
  { id: "0807", name: "Deaglan Myriad Zecharias" },
  { id: "0808", name: "Tanaka Keigo" },
  { id: "0809", name: "Juan Shim" },
  { id: "0810", name: "Adrain Myles Schandré" },
  { id: "0901", name: "Shiloh Hayes" },
  { id: "0902", name: "Mezoya Liu" },
  { id: "0903", name: "Ralph-Prince Theodore" },
  { id: "0904", name: "Maizel Leonhart" },
  { id: "0905", name: "Killian Reed" },
  { id: "0906", name: "Ryder Vaughn" },
  { id: "0907", name: "Shalimar Amari" },
  { id: "0908", name: "Aether Dahlberg" },
  { id: "0909", name: "Violet Bridget" },
  { id: "0910", name: "Elizabeth Rue Wagner" },
  { id: "1001", name: "Aaron Ford Leneghan" },
  { id: "1002", name: "Alia Yrving" },
  { id: "1003", name: "Camille Margaux" },
  { id: "1004", name: "Diana Fincher" },
  { id: "1005", name: "Elleonaire van Dijk" },
  { id: "1006", name: "Ethan Snyder" },
  { id: "1007", name: "Hamengku Alurisjad" },
  { id: "1008", name: "Ieiri Seigen" },
  { id: "1009", name: "Irene Liu" },
  { id: "1010", name: "Isabel Reyes" },
  { id: "1011", name: "Laura Kinney" },
  { id: "1012", name: "Lee Seulong/Dew Lee" },
  { id: "1013", name: "Maivella Aoki" },
  { id: "1014", name: "Naomi Evangeline" },
  { id: "1015", name: "Nero Julien" },
  { id: "1016", name: "Niko Dash-Tanaka" },
  { id: "1017", name: "Rhaenyra" },
  { id: "1018", name: "Sergio Ezekiel" },
  { id: "1019", name: "Venetia Roscent" },
  { id: "1020", name: "Victoire Lyra Lee" },
];

export { batches, members };
