const batches = [
  {
    id: 1,
    name: "The Temps Commission",
    src: "https://com.bimago.media/media/catalog/image/view/product/89856/role/image/size/1500x2240/type/ft-osmr-ng1/f6c607e29956d55da919e89ee3f74fef.webp",
    desc: "As the population of the world is significantly increasing year after year, it became greatly disproportionate to the available resources that can sustain human life. In a dystopian society in 2169, every person stops aging at 25, but is genetically engineered to live off the clock installed on their forearm at birth. Everyone is given exactly 365 days on the clock and the time will start ticking away as soon as they come of age. \n\nTo control the population, the country, New Greenwich, is divided into Time Zones. \n\nThe poor inhabit Time Zone 1; manual labourers who get paid measly, hardly sustaining their living with the ever increasing inflation. Citizens in the Time Zone live off a day's worth of time, often as not, expiring on the streets when their hard-earned time ticks to its last second. \nIn Time Zone 10, the wealth lived lavishly. With centuries to millennia of time in their clocks, they essentially live as immortals; flocking in casinos day in and out, hosting and attending grand parties every night.",
    tags: "dystopian, competition, time as currency, games",
    quote: "The rich can live forever, the poor die young.",
    codename: ["Time Keepers", "Citizens"],
    admins: "Martin Walker, Jerry Rogers",
    members: [
      "T01-001: Iekami Getsuryuu",
      "T01-002: Alessia Devynn Llywelyn",
      "T01-003: Theodore Julien Foster",
      "T01-004: Estelle Illiana",
      "T01-005: W***** R*********",
      "T01:006: Beatrice Amelia",
      "T01-007: S**** S********",
      "T01-008: Maxine Briar",
      "T01-009: Evander Damaris",
      "T01-010: Nala Rivers",
      "T01-011: Valerian Ford",
      "T01-012: E****** I** A****",
      "T01-013: D*** L******",
      "T01:014: Nicolette Bronchard",
      "T01-015: C****** E*****",
      "T01-016: Jeannine",
      "T01-017: Caspian Wilder",
      "T01-0018: Martha Ivory Baker",
      "T01-0019: Morgan Lloyd",
      "T01-020: Madeleine Hampton",
      "T01-021: Zion Alessandre Wilde",
      "T01-022: Samara Dardenne",
      "T01-023: R**** C******",
      "T01-024: Everett Sun",
      "T01-025: O*** D****** A*******",
      "T01-026: A**** L** S*******",
      "T01-027: Ikumi Naoya",
      "T01-028: A***** H*****",
      "T01-029: O***** L***",
      "T01-030: A**** R********",
    ],
    testimony: {
      who: "Onyx Desiree Aphelion",
      pic: "https://uxwing.com/wp-content/themes/uxwing/download/peoples-avatars/businessman-icon.png",
      highlight:
        "The movie reference was so creatively placed,\nit was like a combination of In Time and The Hunger Games?",
      says: "TempsCommission was one of the first few agencies that awakened my love and passion to plot and develop my original character. I was given so many chances to socialize in the way too, and it made me gain a lot of new friends. The movie reference was so creatively placed, it was like a combination of Time and The Hunger Games? I love how the second part was centered on rebellion and revolution. Just as I thought it couldn’t get any better, you guys exceeded all my expectations and gave us a very enjoyable experience!",
    },
  },
  {
    id: 2,
    name: "Defeat the System",
    src: "https://com.bimago.media/media/catalog/image/view/product/89856/role/image/size/1500x2240/type/ft-osmr-ng1/f6c607e29956d55da919e89ee3f74fef.webp",
    desc: "The world had gradually become wicked year after year when the millennium began. Legions of anti-g/vernment groups and crime syndicates came to the surface, operating to resist the g/vernment and commit offences for their own gain, resulting to the compromise of the people's right to security. \n\nEradicating these groups is the g/vernment's longstanding problem. Their modus operandi evolved through the years. Beginning the year 2022, they started communicating openly through radio transmissions, but in unspecified codes and ciphers, making it difficult for the g/vernment to locate their hideouts and intercept the planned attacks. \n\nTo help with the problem, Warwick Intelligence Service is set to form a task force to work towards the complete wipeout of the anonymous groups and ultimately restoring the peace and order in Ostden.",
    tags: "m/litary intelligence, ciphers and codes",
    quote: "Protecting the country, the people, and their interests.",
    codename: ["Task Force Commanders", "Agents"],
    admins: "Martin Walker, Alexander Nolan",
    members: [
      "WIS-003: Iekami Getsuryuu",
      "WIS-004: Nala Rivers",
      "WIS-005: Evander Damaris",
      "WIS-006: Liliane Haynes",
      "WIS-007: O*** D****** A*******",
      "WIS-008: Dylan Briar",
      "WIS-009: Roman Caden Won",
      "WIS-010: Samara Dardenne",
      "WIS-011: Valerian Ford",
      "WIS-012: Enid Lea Schwartz",
      "WIS-013: V***** T******",
      "WIS-014: Madeleine Hampton",
      "WIS-015: Atlas Dufort",
      "WIS-016: Veronica Quinn",
      "WIS-017: Leonard Touissant",
      "WIS-018: S***** L******",
      "WIS-019: Maximus Oliver Wang",
      "WIS-020: Eveline Mae",
      "WIS-021: Xavier Lucille Easton",
      "WIS-022: Arianne Adler",
      "WIS-023: Maximilian Nathaniel",
      "WIS-024: S**** B******",
      "WIS-025: R**** I****** H*******",
      "WIS-026: Chrys Aubine",
      "WIS-027: Killian Pierce",
      "WIS-028: Trixie Leighton",
      "WIS-029: Dalton Leauregard",
      "WIS-030: Judith Jenina Rainsford",
      "WIS-031: Zero Hans Kaizer",
      "WIS-032: A****** Z***** H************",
      "WIS-033: S******* A******",
      "WIS-034: Lunetta Selene",
      "WIS-035: Zion Rand Carter",
      "WIS-036: Keiko",
    ],
    testimony: {
      who: "Iekami Getsuryuu",
      pic: "https://uxwing.com/wp-content/themes/uxwing/download/peoples-avatars/businessman-icon.png",
      highlight:
        "I’m glad I was there to witness all the new games an agency ever created.",
      says: "As a sequel from the first, Defeat The System had me running for my life with more intense tasks. This batch is also the first of many other tasks where we are required to have relations within the batch. I didn’t expect myself to be able to reach the Time Zones 0 at the end, but I’m glad I was there to witness all the new games an agency ever created. 100% would fight against Martin as timekeeper again.",
    },
  },
  {
    id: 3,
    name: "Warwick Intelligence Service",
    src: "https://com.bimago.media/media/catalog/image/view/product/89856/role/image/size/1500x2240/type/ft-osmr-ng1/f6c607e29956d55da919e89ee3f74fef.webp",
    desc: "The world had gradually become wicked year after year when the millennium began. Legions of anti-g/vernment groups and crime syndicates came to the surface, operating to resist the g/vernment and commit offences for their own gain, resulting to the compromise of the people's right to security. \n\nEradicating these groups is the g/vernment's longstanding problem. Their modus operandi evolved througThe world had gradually become wicked year after year when the millennium began. Legions of anti-g/vernment groups and crime syndicates came to the surface, operating to resist the g/vernment and commit offences for their own gain, resulting to the compromise of the people's right to security. \n\nEradicating these groups is the g/vernment's longstanding problem. Their modus operandi evolved through the years. Beginning the year 2022, they started communicating openly through radio transmissions, but in unspecified codes and ciphers, making it difficult for the g/vernment to locate their hideouts and intercept the planned attacks. \n\nTo help with the problem, Warwick Intelligence Service is set to form a task force to work towards the complete wipeout of the anonymous groups and ultimately restoring the peace and order in Ostden.",
    tags: "m/litary intelligence, ciphers and codes",
    quote: "Protecting the country, the people, and their interests.",
    codename: ["Task Force Commanders", "Agents"],
    admins: "Martin Walker, Alexander Nolan",
    members: [
      "WIS-003: Iekami Getsuryuu",
      "WIS-004: Nala Rivers",
      "WIS-005: Evander Damaris",
      "WIS-006: Liliane Haynes",
      "WIS-007: O*** D****** A*******",
      "WIS-008: Dylan Briar",
      "WIS-009: Roman Caden Won",
      "WIS-010: Samara Dardenne",
      "WIS-011: Valerian Ford",
      "WIS-012: Enid Lea Schwartz",
      "WIS-013: V***** T******",
      "WIS-014: Madeleine Hampton",
      "WIS-015: Atlas Dufort",
      "WIS-016: Veronica Quinn",
      "WIS-017: Leonard Touissant",
      "WIS-018: S***** L******",
      "WIS-019: Maximus Oliver Wang",
      "WIS-020: Eveline Mae",
      "WIS-021: Xavier Lucille Easton",
      "WIS-022: Arianne Adler",
      "WIS-023: Maximilian Nathaniel",
      "WIS-024: S**** B******",
      "WIS-025: R**** I****** H*******",
      "WIS-026: Chrys Aubine",
      "WIS-027: Killian Pierce",
      "WIS-028: Trixie Leighton",
      "WIS-029: Dalton Leauregard",
      "WIS-030: Judith Jenina Rainsford",
      "WIS-031: Zero Hans Kaizer",
      "WIS-032: A****** Z***** H************",
      "WIS-033: S******* A******",
      "WIS-034: Lunetta Selene",
      "WIS-035: Zion Rand Carter",
      "WIS-036: Keiko",
    ],
    testimony: {
      who: "Nala Rivers",
      pic: "https://uxwing.com/wp-content/themes/uxwing/download/peoples-avatars/businessman-icon.png",
      highlight:
        "One thing about Walker Archives, they will give you the chance to be someone you wouldn't even think about writing yourself.",
      says: "I loved playing agent! One thing about Walker Archives, they will give you the chance to be someone you wouldn't even think about writing yourself. Me, a translator? I wouldn't have imagined myself as a translator without their storyline and guidance. Oh, I had a badass codename too. The Ivy.",
    },
  },
  {
    id: 4,
    name: "Blanc Private Detectives",
    src: "https://com.bimago.media/media/catalog/image/view/product/89856/role/image/size/1500x2240/type/ft-osmr-ng1/f6c607e29956d55da919e89ee3f74fef.webp",
    desc: "",
    tags: "",
    quote: "",
    codename: ["", ""],
    admins: "",
    members: [
      "WIS-003: Iekami Getsuryuu",
      "WIS-004: Nala Rivers",
      "WIS-005: Evander Damaris",
      "WIS-006: Liliane Haynes",
      "WIS-007: O*** D****** A*******",
      "WIS-008: Dylan Briar",
      "WIS-009: Roman Caden Won",
      "WIS-010: Samara Dardenne",
      "WIS-011: Valerian Ford",
      "WIS-012: Enid Lea Schwartz",
      "WIS-013: V***** T******",
      "WIS-014: Madeleine Hampton",
      "WIS-015: Atlas Dufort",
      "WIS-016: Veronica Quinn",
      "WIS-017: Leonard Touissant",
      "WIS-018: S***** L******",
      "WIS-019: Maximus Oliver Wang",
      "WIS-020: Eveline Mae",
      "WIS-021: Xavier Lucille Easton",
      "WIS-022: Arianne Adler",
      "WIS-023: Maximilian Nathaniel",
      "WIS-024: S**** B******",
      "WIS-025: R**** I****** H*******",
      "WIS-026: Chrys Aubine",
      "WIS-027: Killian Pierce",
      "WIS-028: Trixie Leighton",
      "WIS-029: Dalton Leauregard",
      "WIS-030: Judith Jenina Rainsford",
      "WIS-031: Zero Hans Kaizer",
      "WIS-032: A****** Z***** H************",
      "WIS-033: S******* A******",
      "WIS-034: Lunetta Selene",
      "WIS-035: Zion Rand Carter",
      "WIS-036: Keiko",
    ],
    testimony: {
      who: "Valerian Ford",
      pic: "https://uxwing.com/wp-content/themes/uxwing/download/peoples-avatars/businessman-icon.png",
      highlight:
        "I remember trying to piece together the clues, acting like I had it all figured out, only to be hit with a jaw-dropping twist at the end.",
      says: "Blanc Private Detective—it was one hell of a ride, in the best way. Cracking riddles and suspecting each other—I remember trying to piece together the clues, acting like I had it all figured out, only to be hit with a jaw-dropping twist at the end. We love a good twist, especially when it involves a tangled romance between beautiful women and crime. Frankly speaking, Alexander Nolan deserved his tragic end!",
    },
  },
  {
    id: 5,
    name: "Majority Feed",
    src: "https://com.bimago.media/media/catalog/image/view/product/89856/role/image/size/1500x2240/type/ft-osmr-ng1/f6c607e29956d55da919e89ee3f74fef.webp",
    desc: "",
    tags: "",
    quote: "",
    codename: ["", ""],
    admins: "",
    members: [
      "WIS-003: Iekami Getsuryuu",
      "WIS-004: Nala Rivers",
      "WIS-005: Evander Damaris",
      "WIS-006: Liliane Haynes",
      "WIS-007: O*** D****** A*******",
      "WIS-008: Dylan Briar",
      "WIS-009: Roman Caden Won",
      "WIS-010: Samara Dardenne",
      "WIS-011: Valerian Ford",
      "WIS-012: Enid Lea Schwartz",
      "WIS-013: V***** T******",
      "WIS-014: Madeleine Hampton",
      "WIS-015: Atlas Dufort",
      "WIS-016: Veronica Quinn",
      "WIS-017: Leonard Touissant",
      "WIS-018: S***** L******",
      "WIS-019: Maximus Oliver Wang",
      "WIS-020: Eveline Mae",
      "WIS-021: Xavier Lucille Easton",
      "WIS-022: Arianne Adler",
      "WIS-023: Maximilian Nathaniel",
      "WIS-024: S**** B******",
      "WIS-025: R**** I****** H*******",
      "WIS-026: Chrys Aubine",
      "WIS-027: Killian Pierce",
      "WIS-028: Trixie Leighton",
      "WIS-029: Dalton Leauregard",
      "WIS-030: Judith Jenina Rainsford",
      "WIS-031: Zero Hans Kaizer",
      "WIS-032: A****** Z***** H************",
      "WIS-033: S******* A******",
      "WIS-034: Lunetta Selene",
      "WIS-035: Zion Rand Carter",
      "WIS-036: Keiko",
    ],
    testimony: {
      who: "Koshino Deura",
      pic: "https://uxwing.com/wp-content/themes/uxwing/download/peoples-avatars/businessman-icon.png",
      highlight:
        "I had heard that W is famous for their riddles, but surprisingly, Majority Feed still did amazingly without them.",
      says: "I was still considered a newcomer when Majority Feed happened, and it was only my second batch, as I remember. I had heard that W is famous for their riddles, but surprisingly, Majority Feed still did amazingly without them. It had a social media theme, and I enjoyed seeing people's secrets and embarrassing moments, as well as competing to receive upvotes. I was one of the winners by the end of the batch, so it's understandable why I love it, honestly!",
    },
  },
  {
    id: 6,
    name: "The Bereuenberg",
    src: "https://com.bimago.media/media/catalog/image/view/product/89856/role/image/size/1500x2240/type/ft-osmr-ng1/f6c607e29956d55da919e89ee3f74fef.webp",
    desc: "Bereuenburg, a small town in Georgia, USA, is home to 7,791 residents, ranging from those who grew up in the town to those who chose to call it their home. The town is known for its pleasant weather, natural beauty, and, of course, those delicious peaches. It's a close-knit community where everyone either knows their neighbors or shares some familial connection. \n\nDespite its modest population, Bereuenburg offers everything the locals need: schools, grocery stores, gas stations, shops, pharmacies—you name it. That's why people choose to remain right in town. \n\nFor the working class, they either run their own businesses within the town, work remotely, or commute to neighboring cities like Atlanta, Valdosta, and Tucker. \n\nTruly, there's no place quite like home. It offers both familiarity and security. Until it doesn't. \n\nWhat would you do if one day, a wave of mu/rders and ki/dnappings struck the town, where everyone knew each other, one way or another? The town that once provided a sense of safety and security has become a breeding ground for a string of he/inous acts. The mystery of who the pe/rpetrators could be, even in broad daylight, weigh heavily on the townspeople. They could be your family, friends, and neighbours.",
    tags: "cr/imes, mystery, small town",
    quote: "Keep the doors shut and your one eye open. You could be next.",
    codename: ["Detectives", "Townspeople"],
    admins: "Martin Walker, Jerry Rogers",
    members: [
      "BRN-001: Aaralyne Cyra Anya",
      "BRN-002: Kaleia Serenity Lovelace",
      "BRN-003: Max Laurent",
      "BRN-004: Viviane Leung",
      "BRN-005: Ariel Nieven Levisay",
      "BRN-006: Rhesh Lysander",
      "BRN-007: Axton Reed",
      "BRN-008: Damien Janvier",
      "BRN-009: Mellissa Cathareau Millers",
      "BRN-010: Lynne Odessa Kirstein",
      "BRN-011: Eleianna Ivy Jacqueline",
      "BRN-012: Veronica Quinn",
      "BRN-013: Sazellene Gradie Aberforth",
      "BRN-014: Leonard Huo",
      "BRN-015: L** A******",
      "BRN-016: Sam Keane",
      "BRN-017: Eira Noelle Villeneuve",
      "BRN-018: G******** A********",
      "BRN-019: Lucienne Ryoo",
      "BRN-020: Kaeto",
      "BRN-021: Colleena Zoe",
      "BRN-022: Dezion Emmanuel",
      "BRN-023: Josephine Ingrid Alexandra",
      "BRN-024: Cassius Lim Navarone",
      "BRN-025: Eden Desjardins",
      "BRN-026: Henry Kane",
      "BRN-027: Finn O'Brien",
      "BRN-028: Kit Sommers",
      "BRN-029: Elio Valentine Kim",
      "BRN-030: Edith Grace Millers",
      "BRN-031: James Nathanael Roosevelt",
      "BRN-032: R******* C*****",
      "BRN-033: S**** G****",
    ],
    testimony: {
      who: "Leonard Huo",
      pic: "https://uxwing.com/wp-content/themes/uxwing/download/peoples-avatars/businessman-icon.png",
      highlight:
        "Watching things unfold as I laid out the cards was quite an experience; it was both thrilling and nerve-wracking.",
      says: "Definitely my favorite batch for a reason (and not just because I got to be the main and only antagonist). Everyone cooked REALLY hard even though I too was being cooked, grilled, whatever you name it. Watching things unfold as I laid out the cards was quite an experience; it was both thrilling and nerve-wracking. Hands down one of my top favorite moments of writing in the community. To this day, I’m still amazed at how W thought of the idea to create Bereuenburg in the first place, let alone the riddes, the lore and everything else. Will I do it again? 100000/100. W Forever.",
    },
  },
];

export { batches };
