const batches = [
  {
    id: 1,
    name: "The Temps Commission",
    src: "https://com.bimago.media/media/catalog/image/view/product/89856/role/image/size/1500x2240/type/ft-osmr-ng1/f6c607e29956d55da919e89ee3f74fef.webp",
    desc: "As the population of the world is significantly increasing year after year, it became greatly disproportionate to the available resources that can sustain human life. In a dystopian society in 2169, every person stops aging at 25, but is genetically engineered to live off the clock installed on their forearm at birth. Everyone is given exactly 365 days on the clock and the time will start ticking away as soon as they come of age. \n\nTo control the population, the country, New Greenwich, is divided into Time Zones. \n\nThe poor inhabit Time Zone 1; manual labourers who get paid measly, hardly sustaining their living with the ever increasing inflation. Citizens in the Time Zone live off a day's worth of time, often as not, expiring on the streets when their hard-earned time ticks to its last second. \nIn Time Zone 10, the wealth lived lavishly. With centuries to millennia of time in their clocks, they essentially live as immortals; flocking in casinos day in and out, hosting and attending grand parties every night.",
    tags: "dystopian, competition, time as currency, games",
    quote: "The rich can live forever, the poor die young.",
    codename: ["Time Keepers", "Citizens"],
    admins: "Martin Walker, Jerry Rogers",
    citizens: [
      "T01-001: Iekami Getsuryuu",
      "T01-002: Alessia Devynn Llywelyn",
      "T01-003: Theodore Julien Foster",
      "T01-004: Estelle Illiana",
      "T01-005: W***** R*********",
      "T01:006: Beatrice Amelia",
      "T01-007: S**** S********",
      "T01-008: Maxine Briar",
      "T01-009: Evander Damaris",
      "T01-010: Nala Rivers",
      "T01-011: Valerian Ford",
      "T01-012: E****** I** A****",
      "T01-013: D*** L******",
      "T01:014: Nicolette Bronchard",
      "T01-015: C****** E*****",
      "T01-016: Jeannine",
      "T01-017: Caspian Wilder",
      "T01-0018: Martha Ivory Baker",
      "T01-0019: Morgan Lloyd",
      "T01-020: Madeleine Hampton",
      "T01-021: Zion Alessandre Wilde",
      "T01-022: Samara Dardenne",
      "T01-023: R**** C******",
      "T01-024: Everett Sun",
      "T01-025: O*** D****** A*******",
      "T01-026: A**** L** S*******",
      "T01-027: Ikumi Naoya",
      "T01-028: A***** H*****",
      "T01-029: O***** L***",
      "T01-030: A**** R********",
    ],
    testimony: {
      who: "Onyx Desiree Aphelion",
      pic: "https://uxwing.com/wp-content/themes/uxwing/download/peoples-avatars/businessman-icon.png",
      highlight:
        "The movie reference was so creatively placed,\nit was like a combination of In Time and The Hunger Games?",
      says: "TempsCommission was one of the first few agencies that awakened my love and passion to plot and develop my original character. I was given so many chances to socialize in the way too, and it made me gain a lot of new friends. The movie reference was so creatively placed, it was like a combination of Time and The Hunger Games? I love how the second part was centered on rebellion and revolution. Just as I thought it couldn’t get any better, you guys exceeded all my expectations and gave us a very enjoyable experience!",
    },
  },
  {
    id: 2,
    name: "Defeat the System",
    src: "https://com.bimago.media/media/catalog/image/view/product/89856/role/image/size/1500x2240/type/ft-osmr-ng1/f6c607e29956d55da919e89ee3f74fef.webp",
    desc: "The world had gradually become wicked year after year when the millennium began. Legions of anti-g/vernment groups and crime syndicates came to the surface, operating to resist the g/vernment and commit offences for their own gain, resulting to the compromise of the people's right to security. \n\nEradicating these groups is the g/vernment's longstanding problem. Their modus operandi evolved through the years. Beginning the year 2022, they started communicating openly through radio transmissions, but in unspecified codes and ciphers, making it difficult for the g/vernment to locate their hideouts and intercept the planned attacks. \n\n    To help with the problem, Warwick Intelligence Service is set to form a task force to work towards the complete wipeout of the anonymous groups and ultimately restoring the peace and order in Ostden.",
    tags: "m/litary intelligence, ciphers and codes",
    quote: "Protecting the country, the people, and their interests.",
    codename: ["Task Force Commanders", "Agents"],
    admins: "Martin Walker, Alexander Nolan",
    citizens: [
      "WIS-003: Iekami Getsuryuu",
      "WIS-004: Nala Rivers",
      "WIS-005: Evander Damaris",
      "WIS-006: Liliane Haynes",
      "WIS-007: O*** D****** A*******",
      "WIS-008: Dylan Briar",
      "WIS-009: Roman Caden Won",
      "WIS-010: Samara Dardenne",
      "WIS-011: Valerian Ford",
      "WIS-012: Enid Lea Schwartz",
      "WIS-013: V***** T******",
      "WIS-014: Madeleine Hampton",
      "WIS-015: Atlas Dufort",
      "WIS-016: Veronica Quinn",
      "WIS-017: Leonard Touissant",
      "WIS-018: S***** L******",
      "WIS-019: Maximus Oliver Wang",
      "WIS-020: Eveline Mae",
      "WIS-021: Xavier Lucille Easton",
      "WIS-022: Arianne Adler",
      "WIS-023: Maximilian Nathaniel",
      "WIS-024: S**** B******",
      "WIS-025: R**** I****** H*******",
      "WIS-026: Chrys Aubine",
      "WIS-027: Killian Pierce",
      "WIS-028: Trixie Leighton",
      "WIS-029: Dalton Leauregard",
      "WIS-030: Judith Jenina Rainsford",
      "WIS-031: Zero Hans Kaizer",
      "WIS-032: A****** Z***** H************",
      "WIS-033: S******* A******",
      "WIS-034: Lunetta Selene",
      "WIS-035: Zion Rand Carter",
      "WIS-036: Keiko",
    ],
    testimony: {
      who: "Iekami Getsuryuu",
      pic: "https://uxwing.com/wp-content/themes/uxwing/download/peoples-avatars/businessman-icon.png",
      highlight:
        "I’m glad I was there to witness all the new games an agency ever created.",
      says: "As a sequel from the first, Defeat The System had me running for my life with more intense tasks. This batch is also the first of many other tasks where we are required to have relations within the batch. I didn’t expect myself to be able to reach the Time Zones 0 at the end, but I’m glad I was there to witness all the new games an agency ever created. 100% would fight against Martin as timekeeper again.",
    },
  },
];

export { batches };
